### ISSUE TITLE
Error detected during execution of :CHADdeps

### ISSUE THREAD

**Issue by szbergeron** [ms-jpq/chadtree#104]
![image](https://user-images.githubusercontent.com/7364398/105367396-64f37700-5bce-11eb-8d22-34f2dd300813.png)

This may not be an actual issue but it appears as one while using vim-plug on neovim. Neovim version is v0.5.0-dev+320-g7a611413b.

**Comment by ms-jpq** [comment]
good point, im using the error print function to make a notification or sorts.

i should just add a line saying its not an error

**Comment by ms-jpq** [comment]
added
