### ISSUE TITLE
no notification handler registered for "/home/indeedwatson/.vim/bundle/chadtree/rplugin/python3/chadtree:command:CHADopen"

### ISSUE THREAD

**Issue by indeedwatson** [ms-jpq/chadtree#106]
Just installed the plugin following the read me, I get this error any time I want to open it

**Comment by ms-jpq** [comment]
ohh i think ur on an old version of it, can you please do the following:

remove `chadtree/` and run `:UpdateRemotePlugins` to remove the old code.

Unless you are on windows, which case you have to use the `legacy` branch for now.

**Comment by indeedwatson** [comment]
my bad, must have been that I installed it without the "branch" stuff first, that worked!

ps i love your dog too

**Comment by ms-jpq** [comment]
me to!

so I just added `:UpdateRemotePlugins` thing to the migration docs. I should close this issue for now :)
