### ISSUE TITLE
UpdateRemotePlugins after migration

### ISSUE THREAD

**Issue by nialov** [ms-jpq/chadtree#107]
The documentation for migrating didn't specify that I needed to run `:UpdateRemotePlugins` after migrating to the new version and I had a "phantom" `:CHADopen` command defined by `pynvim` (assumedly).

I apologise that I do not have the full error message but I fixed the error already with `:UpdateRemotePlugins` and I have no log file :(. It was close to this:

~~~
no request handler registered for "/path/to/runtime/rplugin/**/define.vim:CHADopen*"
~~~

So I just suggest adding some note about using `:UpdateRemotePlugins` after migrating if you get the above kind error message. No idea if this is a common error or just specific to my configuration.

**Comment by ms-jpq** [comment]
Thank you ver much!
