### ISSUE TITLE
Comparison to coc-explorer

### ISSUE THREAD

**Issue by fsareshwala** [ms-jpq/chadtree#11]
You may want to add something in your readme about a comparison to COC - explorer. The plugin and even it's bindings are pretty close so for someone coming in you who is comparing a bunch of different file explorer plugins, it might help them to see a comparison of features between the more popular ones.

**Comment by ms-jpq** [comment]
Ya, that is a good idea, but I want to be fair to the other developers so I have to try out all of their features in depth first, so this will probably not be done for a while.

To be totally honest, from just feature list, I think `CHADTree` already has a decent shot at attracting new users.

I got quite a few things in there that's pretty much not found anywhere else

**Comment by lynndylanhurley** [comment]
FWIW over the past week i've been trying 4 of the main NERDTree alternatives, and I prefer CHADTree.

Here's my high level overview:

* NERDTree: I really like it but the performance is insanely bad and the icon / git status integration is very janky
* defx.vim: very performant and stable, but there are no keybindings and I didn't want to deal with the config
* coc-explorer: performant, lots of nice features, but lots of rough edges. would have gone with this, but some strange behavior broke my workflow and CHADTree is a little more simple and straightforward, which is what I'm personally looking for
* fern.vim: didn't like the default keybindings, and my preferred keybindings didn't seem to be possible to map with their system. also felt slightly janky but not as bad as coc-explorer

One thing that CHADTree does better than any of the others is session persistence. For example, if I have a bunch of nested directories expanded and I quit vim, the expansion state is persisted when I re-open vim. defx did this to some degree, but it didn't do it quite as well as CHADTree. The main issue was that in defx when i collapse a directory, it closes all of the children of that directory, whereas in CHADTree it leaves the children in the state that they were in when I re-open the parent. Seems like a minor issue but it was unbelievably annoying with large complicated directories.

**Comment by ms-jpq** [comment]
ok im too lazy to do this gonna close it.

I think CHADTree stands on its merits enough. less time writing comparisons, more time writing code
