### ISSUE TITLE
Allow changing `runtime` dir

### ISSUE THREAD

**Issue by cideM** [ms-jpq/chadtree#110]
I'm using Nix to install Neovim plugins and as such all my plugins live in a read-only directory. `chadtree` therefore can't download its dependencies since it can't write to `runtime`. I think a more idiomatic place for these things would be something from `XDG` anyway, maybe `XDG_RUNTIME_DIR` or `XDG_CACHE_HOME`.

I don't know any python but if you don't have time (but would be willing to accomodate the change) I'd give it a try.

**Comment by ms-jpq** [comment]
sure i will do that, its no biggie. i didnt know nix did that

i put everything under git root only because its easy to cleanly uninstall

**Comment by cideM** [comment]
Yeah I get the point about cleanly uninstalling things. But I think if you use something from the XDG spec for all your download and file writing needs you're actually making your life easier since it's up to the user to clean up their XDG directories. It could even be nice to keep `chadtree` related files even if you nuke your Neovim directory. And I mean the default could remain a path relative to the plugin directory. 

I made the plugin work with Nix regardless by downloading all the dependencies with Nix upfront but now I'm seeing errors because it's trying to write sessions to the same folder.

**Comment by ms-jpq** [comment]
yeah im gonna add an option tomorrow to let u do that. technically there is nothing preventing people from storing their plugins in XDG directories though.

**Comment by ms-jpq** [comment]
PR https://github.com/ms-jpq/chadtree/pull/123

coming soon

**Comment by ms-jpq** [comment]
```vim
let g:chadtree_settings = {'xdg': v:true}
```
