### ISSUE TITLE
Make python path configurable

### ISSUE THREAD

**Issue by stephan-hesselmann-by** [ms-jpq/chadtree#111]
I would like to configure the python interpreter that runs `chadtree` independently of what is configured in PATH as `python3`. This is very useful if `python < 3.8.2` has been configured in PATH for other reasons, e.g. development in a virtual environment.

**Comment by chaudum** [comment]
I think your problem would be mitigated by #114

**Comment by chaudum** [comment]
Hm, I see. `CHADopen` still uses `python3` from the system path, not from `g:python3_host_prog`.

**Comment by stephan-hesselmann-by** [comment]
> Hm, I see. CHADopen still uses python3 from the system path, not from g:python3_host_prog.

Yes exactly. Free configuration is probably not necessary, but it should use `g:python3_host_prog`.

**Comment by chaudum** [comment]
> > Hm, I see. CHADopen still uses python3 from the system path, not from g:python3_host_prog.
> 
> Yes exactly. Free configuration is probably not necessary, but it should use `g:python3_host_prog`.

I'll provide a fix :)

**Comment by ms-jpq** [comment]
thank you @chaudum 

I have merged in everything

**Comment by stephan-hesselmann-by** [comment]
@ms-jpq Did you test the fix? I still have the same problems with `python<3.8.2`. Looking at the code these lines seem very fishy to me

```
local go, _py3 = pcall(vim.api.nvim_get_var, "python3_host_prog")
local py3 = go and _py3 or "python3"
```

I'm not that familiar with Lua but doesn't `py3` evaluate to `true` when `python3_host_prog` is set? (rather than the actual path)

**Comment by stephan-hesselmann-by** [comment]
Just FYI I tested it again after the latest commits and it works now. Thanks for the fix.

**Comment by ms-jpq** [comment]
yeah sorry i made a bad merge when i closed this issue and it erased the line that applied the fix, i noticed it when i was tryint to get it to run on windows later.

thank you for testing! i appreciate it
