### ISSUE TITLE
When execute CHADopen or any command not work?

### ISSUE THREAD

**Issue by TeoDev1611** [ms-jpq/chadtree#112]
I am on windows 10
NVIM v0.4.4
Python 3.8.6

When I run CHADopen or CHADdeps or any command it doesn't work
I restart Vim and update the remote dependencies. What happened?
i installed it like this
Plug 'ms-jpq / chadtree', {'branch': 'chad', 'do': 'python3 -m chadtree deps'}
"

**Comment by neelkarma** [comment]
See #102 - the `chad` branch of CHADTree doesn't work on Windows yet. You can use the `legacy` branch instead.

**Comment by TeoDev1611** [comment]
Thanks i will test

**Comment by ms-jpq** [comment]
yeah windows support is coming on the next RP sorry.

i had to release my huge bundle of work before I got burnt out.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/124

**Comment by ms-jpq** [comment]
windows now works
