### ISSUE TITLE
Error when changing tabs (buffers)

### ISSUE THREAD

**Issue by ecesar88** [ms-jpq/chadtree#116]
Hi, first of all thanks for the amazing plugin! It's reaaaaaaaally fast, seriously.
I'm getting this error when changing tabs:
![image](https://user-images.githubusercontent.com/37763819/105634856-10e6cd80-5e2e-11eb-8c9d-cbdf5c892c66.png)

I'm using [barbar.nvim](https://github.com/romgrk/barbar.nvim) it just adds these cool tabs to the top of the screen: 
![image](https://user-images.githubusercontent.com/37763819/105634875-2825bb00-5e2e-11eb-8b72-0c800eee6f8f.png)

and sometimes when I change tabs: 
![image](https://user-images.githubusercontent.com/37763819/105634896-44c1f300-5e2e-11eb-8575-5ee0b5ddd313.png)

I get the error above.

CHADTree keeps working, it doesn't break, I can hit `C-k` and use it normally afterwards, but it's kinda awkward to have this giant message popping up every once in a while.

I didn't edit the default CHADTree settings, I'm just using it out-of-the box. Might've changed the icons' color (or pack), but that's all.

Thanks in advance.

Edit: Also, here is my init.vim, the one that's on my dotfiles repo is outdated, so here's the newer one: http://ix.io/2NbJ

**Comment by ecesar88** [comment]
UPDATE:
Found another thing that triggers the same error: hovering errors or warnings from [CoC (LSP)](https://github.com/neoclide/coc.nvim). Here's a GIF to demonstrate:

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/37763819/105635712-61602a00-5e32-11eb-875e-0bfcc6346782.gif)

I ran `:checkhealth` just to see if everything was alright, and then it happened.

**Comment by ms-jpq** [comment]
ok this seems like i will need to add something that suppresses expired windows.

i will do that soon, got an infection right now from some stubborn sutures lol

**Comment by ecesar88** [comment]
Nice! Hope you get better soon!

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/120

**Comment by ecesar88** [comment]
Many thanks!

**Comment by ms-jpq** [comment]
wait i havnt even finished merging it yet and u closed the issue?

is it solved when you pulled the branch?

**Comment by ecesar88** [comment]
Actually i didn't try it yet. Was planning to to tonight. But if you say it's solved, then ig it is.

**Comment by ecesar88** [comment]
Hey sorry for the delay. I've been a little busy lately. Just tested it writing some code today and it works very well. The errors are gone. Thank you so much! I think we can close this now. I have another question, guess i'll open another issue regarding it,
