### ISSUE TITLE
Issue on Windows: `No module named 'grp'`

### ISSUE THREAD

**Issue by yngwi** [ms-jpq/chadtree#12]
Hi,
I wanted to try your plugin on Windows but I'm getting an error on `:UpdateRemotePlugins`. I have Python2 and 3 installed with Chocolatey and `:checkhealth` reports that everything is ok. The full error looks like this:

![image](https://user-images.githubusercontent.com/963440/89120726-dd4b6c00-d4b8-11ea-89c4-7babe148983d.png)

Do you have any tips on what to do?

Kind regards,
Daniel

**Comment by ms-jpq** [comment]
Hi there,

I just pushed a fix, can you please update and try again?

https://github.com/ms-jpq/chadtree/commit/bc059d17c5ef7a97b76589149f738a4e79df0e74

**Comment by yngwi** [comment]
It works now, thank you!
