### ISSUE TITLE
Change keymap for chadtree_settings.keymap.new because it isn't working

### ISSUE THREAD

**Issue by JoakoV3** [ms-jpq/chadtree#125]
I don't know if this is a general problem but what it's happening is that when I press the "n" in my vim, it searches for a pattern and I get the error `E486: Pattern not found <pattern>` And the create new file command is not executed. I would like to make a custom remap and update this in the documentation if possible. How can I be able to do that?

**Comment by ms-jpq** [comment]
sorry i made a typo.
the default for the key is `a` not `n`. I fixed it

the default is `a` instead of `n` because `n` and `N` are used to search things

you can rebind it to `n` by setting `chadtree_settings.keymap.new` to `n`
