### ISSUE TITLE
Gutter missing icons even after installing patched fonts.

### ISSUE THREAD

**Issue by FarisArch** [ms-jpq/chadtree#126]
![Screenshot_2021-01-26_18-41-38](https://user-images.githubusercontent.com/74707793/105835554-ea2fbf00-6006-11eb-969c-5a5f30afa211.png)

Fonts I tried : Source Code Pro, JetBrains, Go Mono
I'm on Debian Buster and the terminal used is Terminator.
Here's my init.vim if needed:

![Screenshot_2021-01-26_18-49-50](https://user-images.githubusercontent.com/74707793/105835859-5f02f900-6007-11eb-8ad6-4dc78649bdde.png)

**Comment by ms-jpq** [comment]
wait CHADTree doesnt do gutter icons. its a sidebar plugin, i think you have it confused with something else.

good luck tho!

**Comment by ms-jpq** [comment]
from the looks of it its either ale or gitgutter, im willing to bet its ale

**Comment by FarisArch** [comment]
Thanks, my bad. It wasn't ale fortunately.
