### ISSUE TITLE
`Error detected while processing function CHADon_stder` unending loop

### ISSUE THREAD

**Issue by ajpeacock0** [ms-jpq/chadtree#135]
Reinstalling CHADtree on Windows to verify fix using
```
Plug 'ms-jpq/chadtree', {'branch': 'chad', 'do': ':UpdateRemotePlugins'}
```

Running `:CHADopen` displays the following error
```
Error detected while processing function CHADon_stderr:
line    1:
^M
Please update dependencies using :CHADdeps^M
-^M
-^M
Dependencies will be installed privately inside `chadtree/.vars`^M
`rm -rf chadtree/` will cleanly remove everything^M
Press ENTER or type command to continue
```

However this error immediately reappears upon dismissal. NeoVim had to be closed to entirely dismiss error 

OS: Windows
```
$ nvim --version
NVIM v0.4.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
```

**Comment by ajpeacock0** [comment]
Note that once I quit NeoVim and ran `:CHADdeps`, everything worked well.

**Comment by ms-jpq** [comment]
oh,

as per the migration docs,

```vim
Plug 'ms-jpq/chadtree', {'branch': 'chad', 'do': 'python3 -m chadtree deps'}
```

it asks you to run `:CHADdeps` basically. maybe I should update the docs to say `:CHADdeps` instead of `python3 -m chadtree deps`

since this is an issue with documentation i will close it?

**Comment by ms-jpq** [comment]
I will update the message to be more explicit and say `you need to run this -- :CHADdeps` or something
