### ISSUE TITLE
CHADTree still doesn't work on Windows 10

### ISSUE THREAD

**Issue by neelkarma** [ms-jpq/chadtree#137]
So I install CHADTree with vim-plug, restart `nvim`, run `:CHADdeps` (which works fine), restart `nvim`, and then run `:CHADopen`, and then this happens:
```
Error detected while processing function CHADon_stderr:
line    1:
^M
Please update dependencies using :CHADdeps^M
-^M
-^M
Dependencies will be installed privately inside `chadtree/.vars`^M
`rm -rf chadtree/` will cleanly remove everything^M
Press ENTER or type command to continue
```
And the same error keeps reoccurring. In order to make it stop, I have to close `nvim`. I try running `:CHADdeps` again (which again works fine), but the same thing keeps happening when I run `:CHADopen`.

Environment:
- Windows 10
- NeoVim 0.4.4
- Python 3.9.1
- pynvim 0.4.2

**Comment by ms-jpq** [comment]
shoot did u use `python3_host_prog` because I forgot to handle that for windows.

Disable it for now and I will fix it on my next PR tomorrow

**Comment by neelkarma** [comment]
yep i used
```vim
let g:python3_host_prog = 'C:\Users\asdfjkl\AppData\Local\Programs\Python\Python39\python.exe'
```
in my `init.vim` if that's what you mean - I'll disable it for now

**Comment by SuperCuber** [comment]
Tried using this plugin on my windows machine, when running `:CHADopen` got spammed with
```
Python was not found; run without arguments to install from the Microsoft Store, or disable thsi shortcut from Settings > Manage App Execution Aliases.^M
```
I have `pynvim` installed and `:checkhealth` says that python3 installation is fine.

When I run `python` in a `cmd` window it does open microsoft store but if `:checkhealth` says it's fine it should be fine...

**Comment by ms-jpq** [comment]
humm sorry im not a windows user, i need to look into this. no idea how to “properly” install python for windows.

your problem seem to be that for whatever reason the python executable is not under %PATH%, or perhaps is under a different name.

it should be solved when i add a patch for python3_host_prog tho, then you can simply set that and it should all work.

**Comment by ms-jpq** [comment]
Please give it a spin!

The looping error should also be resolved because apparently unlike bash, batch doesn't propagate error codes. So CHADTree kept thinking everything went well and re-trying to open it.

I manually propagated the error so now it should be ok

**Comment by ms-jpq** [comment]
@SuperCuber 

I think you will still need something like

```vim
let g:python3_host_prog='C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps\python.exe'
```

Because I cannot account for all python install locations, my implementation only works for the one that's "microsoft approved"

**Comment by SuperCuber** [comment]
I wonder, is it possible to use `:python3` command instead of the executable path to make the plugin more flexible?
If not then `python3_host_prog` shouldn't be much of a problem either.

Edit: This is also a problem for the `{ do }` post-install hook, I guess.

**Comment by ms-jpq** [comment]
it works for you now?

`:python3` checks for if you have `pynvim` installed, not where python executable is. 

I guess the `do` command will require you to change `python` to whatever the actual python executable is. I have no control over that. Really, the same thing can happen on unix systems as well, its just that under unix, `python3` is almost always installed as `python3`.

I am not a windows user so I can't say if different python installations will install under different names. So I just default to the microsoft one

**Comment by SuperCuber** [comment]
> it works for you now?

Updating my python to 3.8 :)

> :python3 checks for if you have pynvim installed, not where python executable is.

Yeah but it can also execute code, I was wondering if it's possible to just use it to execute all the python code instead of the executable.

**Comment by ms-jpq** [comment]
Probably not, without running a python subprocess under a python subprocess.

Because CHADTree has to run under a `venv`, and I don't think there is a good way to set the current python process to run under `venv` once it's already up? I know there was some script that does it for `virtualenv`, but not `venv`. Which then would require CHADTree to bootstrap `virtualenv`, and we are back to square 1.

Python packaging is pretty much a quagmire in general. I had to switch from my old `pip --target` method which was more permissive but won't work under microsoft store python.

**Comment by ms-jpq** [comment]
On second thought, it would only be required to run the subporcess under subprocess to boostrap the `venv`. Which isn't too bad. 

Because once `venv` has been bootstrapped, CHADTree will know exactly where the `python.exe` is.

But requiring `pynvim` to just bootstrap `venv` to install `pynvim` in. That's still pretty stupid.

**Comment by SuperCuber** [comment]
I think requiring `pynvim` is not too bad since it's not exactly a rare dependency

**Comment by SuperCuber** [comment]
Installed python3.8 into my `PATH`, now it works even without `python3_host_prog`.

**Comment by ms-jpq** [comment]
thank you so much for getting back to me!
