### ISSUE TITLE
window_options in some cases are applied on non-CHADTree windows

### ISSUE THREAD

**Issue by przepompownia** [ms-jpq/chadtree#145]
I noticed that in some cases my non-chadtree window get styled like CHADtree window: it loses number and sign columns, have enabled `cursorline` etc. Most probably the reason lies on chadtree side. I cannot still precise when this behaviour occurs, but let keep this issue open.

**Comment by przepompownia** [comment]
It occurs after opening a file in new tab.

**Comment by ms-jpq** [comment]
This happens when CHADTree is the last window, and then when you open more windows, they will inherit CHADTree's window options.

A solution would be to restore whatever window options was there natively, when CHADTree is the last window.

I am having an interview coming up soon, so this is gonna be on the back burner for a bit, but thanks for letting me know :D

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/154

**Comment by anasem** [comment]
I still have this problem whenever I open a file in a new tab

**Comment by ms-jpq** [comment]
god damn you guys are awesome

https://github.com/ms-jpq/chadtree/pull/158
I forgot you could even open in new tab haha

**Comment by ms-jpq** [comment]
fixed now

**Comment by Albert-IV** [comment]
Recently tried CHADtree and liking it, but noticed that my number and sign columns are now missing.  

The trigger for these being missing seems to be when the `chadtree_settings` value is set.

### Config that has numbers / gutter signs missing

```
set number
set signcolumn=yes

" ... Later in my config ...

let g:chadtree_settings = { "theme.text_colour_set": "env" }
```

### Fix for settings

```
set number
set signcolumn=yes

" ... Later in my config ...

let g:chadtree_settings = { "theme.text_colour_set": "env" }

" Set again to fix it
set number
set signcolumn=yes
```


### Not setting `chadtree_settings` - line numbers / gutter works

```
set number
set signcolumn=yes

" ... Later in my config ...

" let g:chadtree_settings = { "theme.text_colour_set": "env" }
```
