### ISSUE TITLE
Add support for ryanoasis/vim-devicons

### ISSUE THREAD

**Issue by adelarsq** [ms-jpq/chadtree#16]
I'm a maintainer from the [vim-emoji-icon-theme](https://github.com/adelarsq/vim-emoji-icon-theme) plugin that extends [vim-devicons](https://github.com/ryanoasis/vim-devicons), using icons that are replaced by emojis instead of custom fonts. Will need a lot of work on it, but I'm already using daily.

For NERDTree shows like this:

<img width="347" alt="Captura de Tela 2020-08-04 às 00 04 34" src="https://user-images.githubusercontent.com/430272/89248445-26e5a500-d5e6-11ea-934f-1ac7b362f610.png">

I want to add support for chadtree. To achieve that this plugin needs to use `WebDevIconsGetFileTypeSymbol()` function from the vim-webdevicons plugin to get the icon for the filetype.

Thanks for this cool plugin!

**Comment by ms-jpq** [comment]
cool icons, i can add that as an option under iconset!

do you mind if i add you to the credits under special thanks ?

right now all icons & colours are imported statically via https://github.com/ms-jpq/chadtree/blob/chad/build.py so I guess when i have some time I can import yours that way too.


i could probably set up github action to do once daily import or something :D

**Comment by adelarsq** [comment]
> cool icons, i can add that as an option under iconset!

Thanks. Was a lot (still is) a lot of work to choose the right icons (or almost right).

> do you mind if i add you to the credits under special thanks?

No problem. I'm really grateful.

> right now all icons & colours are imported statically via https://github.com/ms-jpq/chadtree/blob/chad/build.py so I guess when i have some time I can import yours that way too.
> i could probably set up github action to do once daily import or something :D

I think that this works. Also I think about a better way to provide something like this. We have this need also for the [vim-clap](https://github.com/liuchengxu/vim-clap) plugin.

**Comment by ms-jpq** [comment]
Can I just say I really enjoyed the comments, love it

```vimL
let s:iconC = '🐮' " cow because its funny
let s:iconCSharp = '☪️ '
let s:iconCert = '🔑'
let s:iconChangelog = '🍁'
let s:iconClojure = '🦚' " icon based on the Programming Clojure Book's cover
```

**Comment by ms-jpq** [comment]
> Also I think about a better way to provide something like this

Actually there is no need to do that for me, I will do the dirty work. My plan is pretty simple, I will write CI automation that builds Neovim in a Docker image, execute the VimL from your plugin, and export out the icons.

I will do a diff, if the new icons are different, the CI should open a Pull Request for me to manually review just incase something breaks. 

It will take me a while to write this however.

**Comment by adelarsq** [comment]
> Can I just say I really enjoyed the comments, love it

Thanks 😄 

> It will take me a while to write this however.

Nice. But no problem. I will wait for that so I can move from the NERDTree.

**Comment by ms-jpq** [comment]
@adelarsq 

do you notice this happening to other plugins?


![图片](https://user-images.githubusercontent.com/50598611/89300313-df2e4000-d61c-11ea-900f-0ae35268246b.png)

Some Emojis seem double width, and I dont know how do u find out which ones are which ?

`east_asian_width` apperantly doesn't work on emojis

edit: not so much double width as they are eating the single space behind them for some reason, probably because they are too big?

**Comment by ms-jpq** [comment]
The branch is here https://github.com/ms-jpq/chadtree/tree/emoji if you want to play with it

**Comment by adelarsq** [comment]
> do you notice this happening to other plugins?

Yes. This occurs with some emojis. My alternative was to add an extra space on the icon config, but with this occurs some rendering issues with some plugins. For now I keep without to evaluate.

> The branch is here https://github.com/ms-jpq/chadtree/tree/emoji if you want to play with it

How fast. I will use that.

**Comment by ms-jpq** [comment]
wait no, Im no done with that yet, its just an evulation branch, I still need to make sure the folder icons and what not are also emojis or else they look odd.

anyways, I think we will need to figure out how to solve the spacing thing, its honestly kind of an eyesore if things are mis aligned, triggers my inner OCD

**Comment by adelarsq** [comment]
I did an update on the plugin to deal with this for Markdown icon. What you think?

**Comment by adelarsq** [comment]
Are you using iTerm? I notice that for each terminal these fonts have distinct behaviors. My last change makes Kitty terminal buggy.

**Comment by ms-jpq** [comment]
ya we need to figure out a terminal agnostic way to do this, emojis have werid rendering issues between terminals, I am using iTerm2

**Comment by adelarsq** [comment]
Maybe related with https://github.com/kovidgoyal/kitty/issues/2500 I will do some research on this. I'm trying to migrate from iTerm to Kitty and did notice this behavior:

> The solution is for neovim to add support for unicode variation selectors.

**Comment by ms-jpq** [comment]
[unicodedata](https://docs.python.org/3/library/unicodedata.html) doesn't seem to help in python.

and for neovim: `nvim_strwidth` doesn't work either, it gives `1` for `⬇️` and `10` for `🏳️‍🌈`.

**Comment by adelarsq** [comment]
> and for neovim: nvim_strwidth doesn't work either, it gives 1 for ⬇️ and 10 for 🏳️‍🌈.

Wait... is it binary?! Maybe this the problem on NeoVim. I don't know to say about Vim. I will take a look on that.

**Comment by ms-jpq** [comment]
So I merged support for using full iconset into main, I just commented out all references to it in the README, I will add it back in when we work out the kinks.

in the main time you can do to use it by doing

```vimL
lua vim.api.nvim_set_var("chadtree_settings", { use_icons = "emoji" })
```

**Comment by ms-jpq** [comment]
Ok so I managed to set up the CI pipeline to give my self automated branch creation whenever you update

https://github.com/ms-jpq/chadtree/commit/ed43a4506ac9fbe607dea570b60f73cdc967ecf5

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/commit/67e1e252b64048f5eac4a85267097c797ad8dcbb

**Comment by adelarsq** [comment]
@ms-jpq Nice. Thanks for your work on this!
