### ISSUE TITLE
Color issue when opening files

### ISSUE THREAD

**Issue by cuducos** [ms-jpq/chadtree#161]
Hi there.

First of all, thank you so much for this amazing plugin — I'm really enjoying it 💜 

Second, sorry my (Neo)Vim skills are not so helpful and I couldn't debug it properly, so I'm pretty sure this issue might sound vague 😞 

I do appreciate any sort of feedback to improve it 👍 

---

**TLDR** _Sometimes_ (by now I could not identify a pattern other than the first hit to the _return_ key fails to open the file and I have to jit it a second time), when I open a file with the _return_ key, the file opens with a messed up color scheme like that:

![image](https://user-images.githubusercontent.com/4732915/109704347-81d38080-7b64-11eb-8634-92d31074b6e6.png)

If I open the same file with `:e test.py` for example, it looks neat:

![image](https://user-images.githubusercontent.com/4732915/109704291-708a7400-7b64-11eb-9004-9a8382ac442e.png)

The example uses a Python file, but the same happens with any kind of file (even text files).

Any ideas about what I might be doing wrong?

**Comment by michaljanocko** [comment]
Same problem here!

**Comment by ms-jpq** [comment]
sorry for the late reply, i got some irl stuff,

anyhow, i have no idea, it looks like all the colours got inverted though, which is very interesting, ill think about it 

---

In my code, there is a section that parses inverse colours as a possible candidate to apply from your LS_COLORS, which could cause it,

mind posting your `LS_COLORS` from `env` please?

:D 

`echo "$LS_COLORS"`

**Comment by michaljanocko** [comment]
Alright, so I reinstalled CHADtree to test this again and the issue magically disappeared. However, my `$LS_COLORS` are (and always were) empty.

**Comment by ms-jpq** [comment]
ok $LS_COLORS is just something for compatibility reasons, not really necessary. ill close this one <3
