### ISSUE TITLE
Return opens new file in vsplit

### ISSUE THREAD

**Issue by suruaku** [ms-jpq/chadtree#165]
I have chadtree and one file opened in directory X, then I navigate to different directory Y in chadtree and open a new file with return key, the new file opens in vsplit window. Even thought that would be a function of opening a new file with `w` key.

 I have noticed that this happens only with `.js`  files. 

All options I have in chadtree is ` nnoremap <leader>l <cmd>call setqflist([])<cr>`

```
NVIM v0.5.0-dev+1126-g0496b572a
Build type: RelWithDebInfo
LuaJIT 2.0.5
CHADtree commit 641fd747d30fe11d455fc29fcd5c5cd69da4f4db
```

**Comment by lynndylanhurley** [comment]
This just started happening to me as well. I'm not sure why it's happening now but it's driving me crazy

**Comment by ms-jpq** [comment]
ohh, that happens when u have an unsaved file. I just make it a split window, but that seems like a bad option. I should probably send it to background instead

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/179/files
