### ISSUE TITLE
Not an editor command: CHADopen

### ISSUE THREAD

**Issue by janaakhterov** [ms-jpq/chadtree#17]
- Using vim-plug
- Python version 3.8.4
- nvim version 0.4.3

Copied the line from README `Plug 'ms-jpq/chadtree', {'branch': 'chad', 'do': ':UpdateRemotePlugins'}` and pasted that into the vim-plug section. 
Re-launched nvim and ran `PlugInstall`; it did show it installed the plugin. 
Re-launched nvim and ran `:CHADopen` and got the error from the title.

**Comment by ms-jpq** [comment]
Have you installed `pynvim`? I think some other user also had the issue here:

https://github.com/ms-jpq/chadtree/issues/6#issuecomment-667498632

installing `pynvim` via `pip3 install -U pynvim` solved it for them

**Comment by ohmyhub** [comment]
I'm having the same issue mentioned and I can confirm that I have pynvim installed and it is up to date.

I looked at the comment you linked to and that information wasn't able to resolve the issue.

**Comment by janaakhterov** [comment]
@ms-jpq Sorry, forgot to mention that, but yes I did install it before install the plugin.

**Comment by jorgebef** [comment]
Have you checked whether you have Python3 enabled in neovim?
What does your output of `:checkhealth` look like?

**Comment by janaakhterov** [comment]
That seems to have been the issue. Added `let g:python3_host_prog = '/usr/bin/python3'`, restarted vim, updated plugins, restarted vim again and it worked. Icons are off, but I'm guessing I just don't have the correct font installed.
