### ISSUE TITLE
Escape special characters in file names

### ISSUE THREAD

**Issue by 33KK** [ms-jpq/chadtree#174]
When opening "$layout.svelte", CHADtree opens ".svelte"

![h](https://i.shx.gg/KcxhhJ.png)

**Comment by benwoodward** [comment]
Hm, I'm not a chadtree user, this showed up in Google search for me. I'm experiencing the same issue with `fzf.vim`, and opening files from `ranger` via `vim-floaterm`. I'm actually only able to open `$layout.svelte` files by escaping the `$`:

![image](https://user-images.githubusercontent.com/1472981/117084953-9e767980-ad9c-11eb-9ce0-18b940fff0de.png)

https://github.com/vim-airline/vim-airline/issues/2379

Seems like this is either a `zsh` or `neovim` issue 🤔

EDIT: Seems like Svelte team are aware of this problem: https://github.com/sveltejs/kit/issues/1149

**Comment by 33KK** [comment]
@benwoodward it isn't related to zsh and I'm pretty sure it was intended to work like this in neovim. It works in nvim-tree.lua so it is a plugin specific issue.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/181

sorry about the delay its fixed
