### ISSUE TITLE
Causes slowdown over time

### ISSUE THREAD

**Issue by AgentCosmic** [ms-jpq/chadtree#176]
I've tried this plugin for a a while. and noticed that neovim will get slower and slower. Then I stopped using it, and the slow down stopped happening. So I'm pretty sure the slowdown is caused by this plugin. The slowdown will only occur if I run the plugin. If I don't run it, the slow down doesn't happen.

**Comment by aquillano** [comment]
+1

Love the plugin, but CPU usage is high.

**Comment by lynndylanhurley** [comment]
I'm getting the same result. I switched to nvim-tree.lua as an experiment and I don't see the same crazy CPU usage with that plugin.

**Comment by ms-jpq** [comment]
weird, this didn't happen before, I think I accidentally something.

maybe I am polling git too frequently?

**Comment by ms-jpq** [comment]
~~found out why, they changed the LSP thingy so now opening a new window will load in a brand new LSP session.~~

~~lol, which genius did that~~

edit:

seems not to be loading in a million lsps, but some how the nodejs usage goes way up, but im not even using nodejs??

still seems like its somehow affecting the lsps 


edit2:

seems to be creating alot of random buffers, im not sure exactly why tho

edit3:

certain lsps spawn a billion buffers in the background, and `CHADTree` went through every single one of them to check which buffers contain files with `<somename>`.

I guess this was an implementation detail on their part, which I had no idea until now 0.o, o.0

**Comment by lynndylanhurley** [comment]
> maybe I am polling git too frequently?

I have noticed that my git index is often locked when I'm using vim on huge codebases. Sometimes I need to exit vim just to make a commit. Could the frequent git polling be causing that?

**Comment by ms-jpq** [comment]
@lynndylanhurley you can set `options.polling_rate` to a higher value, so you dont get so many git processes running.

I think I mostly fixed the performance issues with huge numbers of `unlisted` buffers with https://github.com/ms-jpq/chadtree/pull/180 though.

It should only use listed buffers now, via changes in https://github.com/ms-jpq/pynvim_pp/commit/2ea4526b4373cdfb375c23962cc503071c4c878d.

---

some LSPs will still cause a slowdown when you open buffers, usually this is a one time only lag spike, when you open the first buffer of it's associated filetype. (acceptable)

but for LSPs like microsoft's `pyright`, ive noticed that it will actually defer loading in assets until you hit a certain threshold for number of buffers open, and once you hit that threshold, it will try to load in like a huge amount of assets at the same time, and this causes additional lag spikes. (less acceptable)

for one of my projects, pyright will load in no background pages initially, but 3000+ background buffers once i hit 3-4 pages open, and this causes a 3-4 second delay, which I am not sure if there is anything I can do to fix.

If the above is blocking the main loop, then i presume without upstream changes, there is nothing I can do.

**Comment by lynndylanhurley** [comment]
Thanks @ms-jpq! I'll update and report back

**Comment by lynndylanhurley** [comment]
@ms-jpq this does seem to be operating much more efficiently for me.

**Comment by ms-jpq** [comment]
ty!

**Comment by maxim-h** [comment]
Doesn't seem like this was the main issue here, but if anyone is still looking for why running `nvim` suddenly consumes so much power and spins up your fans: 

In my case cranking up `options.polling_rate` really helped. `git` was running some expensive operation every other second. 

This does make chadtree less responsive to filsystem changes as well, but doesn't bother me too much. ~~Although considering the authors obsession with fast things maybe it's worth allowing polling the git and fiilesystem at different rates.-~~
edit: Actually, scratch that last bit. It would probably look even more annoying.
