### ISSUE TITLE
user request: search instead of filtering 

### ISSUE THREAD

**Issue by ms-jpq** [ms-jpq/chadtree#20]

**Comment by ms-jpq** [comment]
maybe i can use ‘fd’ or ‘find’

**Comment by joereynolds** [comment]
In my experience the order of preference for finding files would be

- First try `fd`
- Fallback to ripgrep (`rg`) (Also good for listing files believe it or not)
- Finally use `find` as a last resort

:)

**Comment by krehwell** [comment]
I think you can use plugin such `ctrl+p` for this

**Comment by ms-jpq** [comment]
this can use `grepprg`

will implement this after refactor to run extension in its own process

**Comment by ms-jpq** [comment]
Closing it for now. I don't see a platform independent way to do this besides arbitrary command execution.
