### ISSUE TITLE
What is it in commit history?

### ISSUE THREAD

**Issue by vatosarmat** [ms-jpq/chadtree#206]
What is this for? This confuses some people and they chose another file explorer plugins
```
CI (AGP) - 2021-07-06 00:28
CI (AGP) - 2021-07-05 00:25
CI (AGP) - 2021-07-04 00:26
```

**Comment by Groctel** [comment]
I'm more concerned by commits like "wrf" "okie" "cool" "kk" and similar...

**Comment by ms-jpq** [comment]
im lazy and i type in random stuff to get git to shut up, If im not getting paid, im not gonna go write "proper" commit messages.

the `CI - *` thing is from the fact that I made a bot that pushes all my repos once a day so I get to use github's free CI forever.

**Comment by Groctel** [comment]
Thanks for your clarification. As I understand, you're not caring about the quality of the free software you develop if you aren't contracted to write it. I don't get why anyone would do that, but to me that's more than enough reason to not rely on chadtree. Anyways, this is just a small personal rant. Good luck on your projects :)

**Comment by vatosarmat** [comment]
As a **Chad** he can behave as he pleases without regard to someone else's opinion

**Comment by ms-jpq** [comment]
> Thanks for your clarification. As I understand, you're not caring about the quality of the free software you develop if you aren't contracted to write it. I don't get why anyone would do that, but to me that's more than enough reason to not rely on chadtree. Anyways, this is just a small personal rant. Good luck on your projects :)

Yes, the quality of my code goes up automatically if I write `Added sql style transaction - retry mechanic` instead of `lol`.

**Comment by mattleong** [comment]
Maybe not the quality of the code itself, but the quality of the project will likely suffer.

**Comment by mattleong** [comment]
> > Thanks for your clarification. As I understand, you're not caring about the quality of the free software you develop if you aren't contracted to write it. I don't get why anyone would do that, but to me that's more than enough reason to not rely on chadtree. Anyways, this is just a small personal rant. Good luck on your projects :)
> 
> 
> 
> Yes, the quality of my code goes up automatically if I write `Added sql style transaction - retry mechanic` instead of `lol`.
> 
> 
> 
> 

Maybe not the quality of the code itself, but the quality of the project will likely suffer.

**Comment by Artturin** [comment]
> the `CI - *` thing is from the fact that I made a bot that pushes all my repos once a day so I get to use github's free CI 

hello, the inactivity time is 60 days without activity so the bot could do it once every 59 days

i also found https://twitter.com/btskinn/status/1339602644642328577?s=20
> Or even just a cronned action on a stub side branch that does a:
```
git commit --amend --no-edit
git push -f
```
