### ISSUE TITLE
how can i use this as a replacement for spacevim file manager ( defx, or others )

### ISSUE THREAD

**Issue by woss** [ms-jpq/chadtree#209]
although i use vim i am still a beginner with configuring it. any help is appreciated

**Comment by da-moon** [comment]
you can look into my Spacevim config [repository](https://github.com/da-moon/SpaceVim.d/blob/master/autoload/before/spacevim/filemanager.vim#L10)

**Comment by ms-jpq** [comment]
yeah ill close this one ^

thanks

**Comment by woss** [comment]
oh, i'm sorry i didn't answer or react! it completely slipped in the vortex of notifications in github :(

Thanks for the link, I rechecked it now and I found what I was looking for!

Thanks again.

**Comment by da-moon** [comment]
@ms-jpq actually, there is a strange problem I am facing with Neovim on one of my machines.
After running `CHADdeps` ; I can't start neovim by running `nvim` in my terminal emulators. I can start neovim with Chadtree using `neovide` though. 
The interesting part is that ChadTree works on my other laptop with the exact same config and apps ; both laptops are running ArchLinux.

Would you happen to know any reason why nvim may freeze ? even `nvim --version` does not work.
