### ISSUE TITLE
[Question] Copy to the same directory (with different filename)

### ISSUE THREAD

**Issue by ceuk** [ms-jpq/chadtree#21]
Hey, is there any way to do the above?

**Comment by ms-jpq** [comment]
Nyet, not yet, I will add this to the todo list

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/72

will close

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/72
