### ISSUE TITLE
Auto Start CHADtree 

### ISSUE THREAD

**Issue by atticusmatticus** [ms-jpq/chadtree#223]
I like to simply open `nvim` when I'm in my working directory and then open files from CHADTree rather than `nvim file_name`. Is there a way to run `:CHADopen` when vim launches so I don't have to type `<leader>v` or `:CHADopen` every time I launch `nvim`?

**Comment by aloussase** [comment]
You can just set an autocmd like this

```viml
autocmd VimEnter * CHADopen
```

**Comment by akkesm** [comment]
I was looking for a way to open CHADtree only in certain situations and I found that NERDtree[ has documentation for this](https://github.com/preservim/nerdtree/#how-do-i-open-nerdtree-automatically-when-vim-starts). Just replace the command to run.

**Comment by atticusmatticus** [comment]
> I was looking for a way to open CHADtree only in certain situations and I found that NERDtree[ has documentation for this](https://github.com/preservim/nerdtree/#how-do-i-open-nerdtree-automatically-when-vim-starts). Just replace the command to run.

@akkesm I can't get the 4th option to work:
```vim
" Start NERDTree. If a file is specified, move the cursor to its window.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * NERDTree | if argc() > 0 || exists("s:std_in") | wincmd p | endif
```

where I've altered it to be the following:
```vim
" Start NERDTree. If a file is specified, move the cursor to its window.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * CHADopen | if argc() > 0 || exists("s:std_in") | wincmd p | endif
```

I get this error when I launch neovim with the above lines enabled.
```
unrecognized arguments: if argc() > 0 || exists("s:std_in") | wincmd p | endif
```

**Comment by akkesm** [comment]
> `unrecognized arguments: if argc() > 0 || exists("s:std_in") | wincmd p | endif`

It looks like `CHADopen` is trying to interpret the rest of the line as arguments (which NERDtree doesn't do). I'm not sure how to prevent it.

**Comment by aloussase** [comment]
You can use a function in the autocmd, maybe something like this

```viml
function s:chadOpen()
  CHADopen
  if argc() > 0  || exists("s:std_in")
    wincmd p
  endif
endfunction

autocmd VimEnter * call s:chadOpen()
```
