### ISSUE TITLE
How to have a different coloured background?

### ISSUE THREAD

**Issue by samrathchadha** [ms-jpq/chadtree#225]

**Comment by im-n1** [comment]
@ms-jpq can you please enlight us on this? Already implemented or waiting for this feature?

**Comment by ms-jpq** [comment]
hey sorry thats decided your own theme not anything on my end

**Comment by im-n1** [comment]
yea sure we can configure that but we need to know whats the "keyword" of  background region we put into "highlight" directive to theme spec

the thing is the chadtree background should be different from normal buffer background so you can theme only chadtree background without affecting the rest

**Comment by cwqt** [comment]
```vim
au BufEnter * if &ft ==# 'CHADTree' | set winhighlight=Normal:BufferTabpageFill | endif
```

set `BufferTabpageFill` to whatever highlight you want

![image](https://user-images.githubusercontent.com/61694629/150398986-153a8681-d19f-4438-80a8-63aa9e99b6d0.png)

**Comment by samrathchadha** [comment]
That's pretty cool, and it works, I'll close this now
