### ISSUE TITLE
Is there an option to close chadtree if it is the last window opened?

### ISSUE THREAD

**Issue by vinoff** [ms-jpq/chadtree#239]
Other file managers have the option of automatically closing when there are no more windows opened. Is there such an option for chadtree?

Say I have chadtree and a test.py opened. I do :q on test.py. By default, vim doesn't close as chadtree is still opened. I would like vim to close.

**Comment by Ollyxs** [comment]
You can just set an autocmd like this

`autocmd BufEnter * if (winnr("$") == 1 && &filetype == "CHADTree") | q | endif`

**Comment by vinoff** [comment]
Thank you!
