### ISSUE TITLE
Add image preview.

### ISSUE THREAD

**Issue by glepnir** [ms-jpq/chadtree#24]
Please check here. https://github.com/Shougo/defx.nvim/issues/220

**Comment by ms-jpq** [comment]
wait you are literally the same person. LOL

ill maybe add this but as a lower priority than other requested features which have higher ROI

**Comment by glepnir** [comment]
It is OK，because i use mac …It doesn't matter for me.

--------------原始邮件--------------
发件人：":D "<notifications@github.com&gt;;
发送时间：2020年8月5日(星期三) 凌晨1:59
收件人："ms-jpq/chadtree" <chadtree@noreply.github.com&gt;;
抄送："Raphael "<glepnir@gopherhub.org&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [ms-jpq/chadtree] Add image preview. (#24)
-----------------------------------

 

 
wait you are literally the same person. LOL
 
ill maybe add this but as a lower priority than other requested features which have higher ROI
