### ISSUE TITLE
CHADTree seems to convert file's name to lowercase

### ISSUE THREAD

**Issue by duydang2311** [ms-jpq/chadtree#242]
Greetings!
I'd like to make an issue of when I open a file by CHADTree, my file is loaded into buffer but its name is converted to lowercase, so once I execute `:w`, the file name would be overwritten as lowercase on the disk.
before `:w` (even lualine and bufferline shows it as lowercase):
![before](https://user-images.githubusercontent.com/34796192/133279032-271be3d7-ccbd-427d-be06-53a7c653dbb1.png)
![image](https://user-images.githubusercontent.com/34796192/133279617-52634153-1510-41a8-8af1-aba03870e883.png)
![image](https://user-images.githubusercontent.com/34796192/133279758-f1edcc22-83d2-454d-ac8e-d83338693960.png)

after `:w`:
![after](https://user-images.githubusercontent.com/34796192/133279041-0c5c9673-fcfd-4321-aa76-296ec96eb5b1.png)

Why do I think it's CHADTree related? I simply did these steps to prove that this is only caused by CHADTree:
- Run nvim without CHADTree plugged, open my file by original vim explorer and it preserves my filename.
- More further, I try plugging NERDTree again, open the same file and my filename is preserved too.

I haven't had this issue before, maybe new updates broke it or maybe I just installed Windows 11 Beta.

**Comment by aloussase** [comment]
I am also having this issue and think it is related to CHADtree

**Comment by RefusesNames** [comment]
I am having the same problem with Windows 10, so it does not depend on the Windows version.

**Comment by duydang2311** [comment]
Looks like this is caused by the behaviour of `os.path.normcase` on Windows.
