### ISSUE TITLE
Icon colours not working

### ISSUE THREAD

**Issue by StarlingC** [ms-jpq/chadtree#249]
Colours are not showing for devicons.

It's very likely something to do with my set up but I can't for the life of me figure out how to get icon colours.

![pic-selected-211007-2023-17](https://user-images.githubusercontent.com/53155160/136452172-da1918c8-e2b1-4373-8221-2209c279d333.png)

I've tried multiple terminal emulators, multiple colour schemes but the draw is always monochrome.

I obviously don't need colours but they look so good in the screenshots it bothers me that I can't get them to work.

Amazing plugin. I absolutely love using it!

**Comment by notsatvrn** [comment]
whats your current configuration, because im actually interested in how to disable the icon colors...

**Comment by StarlingC** [comment]
I couldn't tell you what would help. I've tried changing everything.
I've cleared my `init.vim` file loading just CHADtree.
I've tried it on my main arch distribution and I tried it on zorin OS (ubuntu).
I tried it on mac but couldn't get any icons to show let alone colours (couldn't get them to show for anything in the terminal, not just CHADtree).
I've installed multiple ttfs ([3270 Nerd Fonts](https://www.nerdfonts.com/font-downloads) was the latest).
I've installed LS_COLORS to see if I could colour the text but that didn't work.
I tried it on alacritty, xterm, st, gnome terminal, even a tty.
I've tried it with transparent background and without.
I'm not sure what else I can change.
I thought I was missing a step in the installation but it sounds like you had the colours appearing from the start?

**Comment by notsatvrn** [comment]
hm
do you have termguicolors enabled?

**Comment by notsatvrn** [comment]
@Codeatron5000 i can think of maybe a couple reasons why it isnt working for you
if you dont use neovim that might cause issues
if you use neovim, set termguicolors

**Comment by StarlingC** [comment]
@satyrnsstuff That's it.
When I turn on termguicolors it works perfectly.
Although now dylanaraps/wal.vim no longer works. Such is life.

Thanks for the advice. Sorry it doesn't help your issue.
