### ISSUE TITLE
Getting ? for icons

### ISSUE THREAD

**Issue by AkalUstat** [ms-jpq/chadtree#25]
Great Plugin! i love it

One problem is that for most of the files i just get ? for icons. Is there like an install step i missed or do i have to install the icons separately
![Screen Shot 2020-08-04 at 10 09 38 AM](https://user-images.githubusercontent.com/43657841/89323571-c16fd380-d63a-11ea-931b-b706144fa7b2.png)

**Comment by joereynolds** [comment]
If the icons aren't a big deal you can do:

```
let g:chadtree_settings = {"use_icons": 0 }
```
That's what fixed it for me.

**Comment by ms-jpq** [comment]
sorry, I should have mentioned this in the README

you will need a patched font with builtin icons, they are usually found here 

https://github.com/ryanoasis/nerd-fonts

not all fonts there will contain all icons though, i found one or two missing at times, but i think the majority should support all icons

**Comment by ms-jpq** [comment]
added to README

https://github.com/ms-jpq/chadtree/commit/68696f8c69e5388d39f2d6e14b0e73f1760de166
