### ISSUE TITLE
 clean up the repo

### ISSUE THREAD

**Issue by glepnir** [ms-jpq/chadtree#26]
Why set so much gif into the repo.. It makes repo size large. you can upload your gif into an issue. then copy the image url and set them into wiki page.

**Comment by ms-jpq** [comment]
😯，我发现你的地区是国内。

我可以加一个国内景象，你可以推荐一个国内的git网站吗？

**Comment by glepnir** [comment]
…为啥要放国内…gitee或者gitea吧，我不怎么用国内的就知道这2个…

--------------原始邮件--------------
发件人：":D "<notifications@github.com&gt;;
发送时间：2020年8月5日(星期三) 凌晨2:29
收件人："ms-jpq/chadtree" <chadtree@noreply.github.com&gt;;
抄送："Raphael "<glepnir@gopherhub.org&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [ms-jpq/chadtree]  clean up the repo (#26)
-----------------------------------

 

 
，我发现你的地区是国内。
 
我可以加一个国内景象，你可以推荐一个国内的git网站吗？

**Comment by ms-jpq** [comment]
国内GitHub不是很慢吗？

**Comment by glepnir** [comment]
有点…有代理啊…不过装插件什么的都还好吧…GIF…我都是创建个issue放进去然后拷贝github的image url地址这样打开是可以放大看的，你这样放点开也是到GIF目录下，效果不怎么好。要减小repo大小也挺麻烦的…

--------------原始邮件--------------
发件人：":D "<notifications@github.com&gt;;
发送时间：2020年8月5日(星期三) 凌晨2:40
收件人："ms-jpq/chadtree" <chadtree@noreply.github.com&gt;;
抄送："Raphael "<glepnir@gopherhub.org&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [ms-jpq/chadtree]  clean up the repo (#26)
-----------------------------------

 

 
国内GitHub不是很慢吗？
