### ISSUE TITLE
Start vim on a folder `vim .`

### ISSUE THREAD

**Issue by dadaphl** [ms-jpq/chadtree#262]
I would like vim to display a full-window of chadtree automatically when opening vim with a folder as argument (`vim .`) or opening a folder from within vim (`:e .`). I'm used to this behavior form NERDTree

Without chadtree
`vim .`
![Screenshot from 2021-11-06 15-18-36](https://user-images.githubusercontent.com/415536/140612974-09b023a8-2807-4036-920b-7158efe2a6f5.png)

With NERDTree
`vim .`
![Screenshot from 2021-11-06 15-27-11](https://user-images.githubusercontent.com/415536/140613129-3899013a-a8a0-4774-b4da-f5095745a4fe.png)

With chadtree
![Screenshot from 2021-11-06 15-19-19](https://user-images.githubusercontent.com/415536/140612984-c6ed00d0-54d7-414c-b356-33bb42868c2c.png)

**Comment by declancm** [comment]
Try adding the following to your .vimrc as it worked for me 

```viml
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists('s:std_in') |
    \ execute 'CHADopen' | execute 'cd '.argv()[0] | endif
```

**Comment by dadaphl** [comment]
Thank you very much! That solves the issue for me.
