### ISSUE TITLE
CHADTree_settings.keymap.tertiary example how to?

### ISSUE THREAD

**Issue by danshumaker** [ms-jpq/chadtree#269]
How do we set a different tertiary keybinding? I am not able to get the example to work.  I'm on a Mac so the default `<m-enter>` does nothing.   (Most tree browsers use \"\<Ctrl-t\"\> for :tabnew mapping.

I'm trying to do this: (in ~/.config/nvim/lua/settings.lua file)

```lua
local chadtree_settings = { "keymap.tertiary":"M" }
vim.api.nvim_set_var("chadtree_settings", chadtree_settings)
```
But am getting a lua syntax error on the colon on the first line.  I've also tried an equal sign:

In my ~/.config/nvim/lua/settings.lua file:
```lua
local chadtree_settings = { "keymap.tertiary"="M" }
vim.api.nvim_set_var("chadtree_settings", chadtree_settings)
```

**Comment by grdl** [comment]
See the [note in the docs](https://github.com/ms-jpq/chadtree/blob/chad/docs/CONFIGURATION.md#shorthand):
> Note in lua, you will need to quote your keys like so:
> { ["dog.puppy"] = 2 }

So, your config needs to look like this:
```
local chadtree_settings = { ["keymap.tertiary"] = "M" }
vim.api.nvim_set_var("chadtree_settings", chadtree_settings)
```

**Comment by danshumaker** [comment]
Thank you @grdl . It looks like this almost worked. However I get this error:
![2021-12-21_10-35-23](https://user-images.githubusercontent.com/358833/146956822-36fd5651-9fde-48c7-976c-05df503f950d.png)

after I set the options to:
```lua
local chadtree_settings = { ["keymap.tertiary"] = "<c-t>" }
vim.api.nvim_set_var("chadtree_settings", chadtree_settings)
```

**Comment by ms-jpq** [comment]
`local chadtree_settings = { ["keymap.tertiary"] = {"<c-t>"} }`

**Comment by ms-jpq** [comment]
since the keymaps support multiple mappings, it needs to be an array instead of a string
