### ISSUE TITLE
Nice project! How do I configure the default columns that chard tree takes?

### ISSUE THREAD

**Issue by ingjieye** [ms-jpq/chadtree#29]
For NERDTree there's a `NERDTreeWinSize` to configure the default columns. How do I do that on the chardtree?

**Comment by ms-jpq** [comment]
```vimL
lua vim.api.nvim_set_var("chadtree_settings", { width = 420 })
```

**Comment by xaotag** [comment]
![image](https://user-images.githubusercontent.com/40427877/151760811-1e6af5c1-6eb6-471c-bb11-cf1b78c2805e.png)
.....

**Comment by berendsliedrecht** [comment]
```sh
lua vim.api.nvim_set_var("chadtree_settings", { view = { width = 420 } })
```

is correct.
