### ISSUE TITLE
Installing using Packer 

### ISSUE THREAD

**Issue by shriharip** [ms-jpq/chadtree#290]
Hi, Could you tell me how I can use Packer / init.lua to install this plugin. Thanks.

**Comment by declancm** [comment]
Try adding this to your plugins.lua or wherever:

```Lua
use {
    "ms-jpq/chadtree",
    branch = "chad",
    run = "python3 -m chadtree deps"
}
```

**Comment by UltiRequiem** [comment]
> Try adding this to your plugins.lua or wherever:
> 
> ```lua
> use {
>     "ms-jpq/chadtree",
>     branch = "chad",
>     run = "python3 -m chadtree deps"
> }
> ```

This is the way.

@shriharip  could you close the Issue?
