### ISSUE TITLE
How to use lua to modify the default key 

### ISSUE THREAD

**Issue by xaotag** [ms-jpq/chadtree#292]
![image](https://user-images.githubusercontent.com/40427877/151766541-bfdd754f-95f2-4935-9a73-3e782dffcf38.png)

**Comment by suruaku** [comment]
AFAK defining keymaps with Lua is a bit tedious(better support coming in the future). For now, a good solution is to just use `.vim` file and in your `init.lua` you can do `vim.cmd 'source ~/.config/nvim/mappings.vim'`
