### ISSUE TITLE
Show the tree on the right side

### ISSUE THREAD

**Issue by UltiRequiem** [ms-jpq/chadtree#295]
I'm reading the docs but I don't find any option to do this 😔 

Example 👇

![image](https://user-images.githubusercontent.com/71897736/156859323-38652599-4f09-40cd-af5c-b4cb43fdf745.png)

**Comment by suruaku** [comment]
```
let g:chadtree_settings = {
  \ "view.open_direction": "right",
\}
```

[docs](https://github.com/ms-jpq/chadtree/blob/chad/docs/CONFIGURATION.md#chadtree_settingsview)

**Comment by UltiRequiem** [comment]
Thanks!
