### ISSUE TITLE
How to close CHADhelp window?

### ISSUE THREAD

**Issue by imcvampire** [ms-jpq/chadtree#297]
I've tried `ESC` and `q` but none works

**Comment by suruaku** [comment]
If you are inside CHADtree window use default `q` [docs](https://github.com/ms-jpq/chadtree/blob/chad/docs/KEYBIND.md#chadtree_settingskeymapquit)

If you are inside another window use CHADopen command, you can map it to leader+v with `nnoremap <leader>v <cmd>CHADopen<cr>`
