### ISSUE TITLE
Wrong of folder icon 

### ISSUE THREAD

**Issue by glepnir** [ms-jpq/chadtree#30]
See this pic . The expanded folder icon is set to the unexpanded folder
![image](https://user-images.githubusercontent.com/41671631/89372332-72986b80-d718-11ea-8503-eec382188425.png)

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/commit/ed43a4506ac9fbe607dea570b60f73cdc967ecf5

**Comment by glepnir** [comment]
@ms-jpq Ok. Why doesn't provide highlight group. It will be useful to match colorscheme.

**Comment by ms-jpq** [comment]
我其实一个颜色都没有设。

用的是你的`$LS_COLOR`, 和github的[linguist](https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml).

`quickfix` 和 `git-status` 用的是vim的`Label`和`Comment`highlight组。那两个可以用户设置。

如果要加highligh组的话，只有文件夹可以添加，因为linguist已经跟所有的文件上色了。

**Comment by glepnir** [comment]
嗯。我知道。所以我配了下`$LS_COLORS`。但是看起来某些地方需要细调整。有些颜色奇奇怪怪的。其实提供高亮组能更好的匹配主题。不过只是建议。目前也能接受。
![image](https://user-images.githubusercontent.com/41671631/89373507-737ecc80-d71b-11ea-8ec6-b291fe06fc5c.png)

**Comment by ms-jpq** [comment]
humm, 的确有点丑。 https://github.com/ms-jpq/chadtree/issues/32

我可以嫁一个颜色设置，覆盖`LS_COLOR`

**Comment by glepnir** [comment]
这个`嫁`好出戏啊2333. 类似defx比较简单。说实话除了这个go的icon颜色。。其他的hmm

**Comment by ms-jpq** [comment]
请问`2333`是设么意思，我中文大概只有小学生水平。

**Comment by glepnir** [comment]
猫扑表情，编号2333 代表大笑。网络用语比较二次元。
![v2-e5351b37e60f4b499e33a8c9c4c8ed03_hd](https://user-images.githubusercontent.com/41671631/89374326-a3c76a80-d71d-11ea-9412-f301bbff1660.gif)

**Comment by ms-jpq** [comment]
oh
