### ISSUE TITLE
A question: How to move cursor from the window back to CHADtree

### ISSUE THREAD

**Issue by shriharip** [ms-jpq/chadtree#300]
Hi,

Suppose I open the file in a window and then want to move the cursor from the file back to tree, how can I do that without closing the CHADTree.

thanks

**Comment by suruaku** [comment]
CHADtree is just a window. See this answer [How does one switch between windows on VIM?](https://superuser.com/questions/280500/how-does-one-switch-between-windows-on-vim)

You can make it a bit faster with this remap which will allow you to move between windows by holding Ctrl and pressing h/j/k/l 
```
" Window navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
```

**Comment by shriharip** [comment]
Thanks again.
