### ISSUE TITLE
How to config theme?

### ISSUE THREAD

**Issue by MrZLeo** [ms-jpq/chadtree#305]
I read the docs, but I still don't get it how to config my theme?

I create a file named `chadtree.lua` and write:

```lua
local chadtree_settings = { ["chadtree_settings.theme.text_colour_set"] = { "nord" } }
vim.api.nvim_set_var("chadtree_settings", chadtree_settings)
```

And it didn't work.

Could you give a example of configuration?

Thanks!!

**Comment by mad-briller** [comment]
you need to use ls_colors:

http://www.bigsoft.co.uk/blog/2008/04/11/configuring-ls_colors

**Comment by mrluisfer** [comment]
> 
I did something like this and it works
![ChadTree Config Preview](https://user-images.githubusercontent.com/65029792/171459144-f6a8f318-2975-4e8f-a0c2-e9e6abbf0386.png)

**Comment by MrZLeo** [comment]
> I did something like this and it works
> ![ChadTree Config Preview](https://user-images.githubusercontent.com/65029792/171459144-f6a8f318-2975-4e8f-a0c2-e9e6abbf0386.png)

Thank you! It works for me!
