### ISSUE TITLE
What font was used in the screenshots?

### ISSUE THREAD

**Issue by iktefish** [ms-jpq/chadtree#310]
I apologize for creating an issue asking such a silly question. I've been using CHADTree for a while and its awesome, but I couldn't help but ask what font you used in the screenshots. It looks amazing.

**Comment by Auratelience** [comment]
Looks like [SF Mono](https://developer.apple.com/fonts/) to me.

**Comment by iktefish** [comment]
Ah yes this seems to be it. Thanks.
