### ISSUE TITLE
出现一些重影

### ISSUE THREAD

**Issue by glepnir** [ms-jpq/chadtree#33]
第一次打开好像没什么问题。后续打开会在右侧出现一些重影。gif好像丢帧了。不知道能不能看出来
![test](https://user-images.githubusercontent.com/41671631/89378673-ed688300-d726-11ea-928d-764be62f3c2c.gif)

**Comment by glepnir** [comment]
gif 容易丢帧。 这样video比较明显了。
https://imgur.com/gallery/dNBy68j

**Comment by ms-jpq** [comment]
😯，在kitty上这门明显？

我iTerm2上好像看不出来，看了终端之间的差别比较大

**Comment by glepnir** [comment]
也试过iterm2 也挺明显的 。kitty性能还有其他的表现上比iterm2好很多~~。 偶尔会出现invalid window id的bug~~

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/issues/39#issuecomment-670650181

应该👌

**Comment by glepnir** [comment]
感觉要修修补补的地方还挺多的…

--------------原始邮件--------------
发件人："i love my dog "<notifications@github.com&gt;;
发送时间：2020年8月8日(星期六) 凌晨2:28
收件人："ms-jpq/chadtree" <chadtree@noreply.github.com&gt;;
抄送："Raphael "<glepnir@gopherhub.org&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [ms-jpq/chadtree] 出现一些重影 (#33)
-----------------------------------

 

 
#39 (comment)
 
应该

**Comment by ms-jpq** [comment]
第一次写Vim插件，缺乏经验

**Comment by glepnir** [comment]
要写doc文档哟，不用都发到readme，remoteplugin多多少少都有点问题

--------------原始邮件--------------
发件人："i love my dog "<notifications@github.com&gt;;
发送时间：2020年8月8日(星期六) 凌晨2:43
收件人："ms-jpq/chadtree" <chadtree@noreply.github.com&gt;;
抄送："Raphael "<glepnir@gopherhub.org&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [ms-jpq/chadtree] 出现一些重影 (#33)
-----------------------------------

 

 
第一次写Vim插件，缺乏经验
