### ISSUE TITLE
Question: How do I get a terminal like this showcase?

### ISSUE THREAD

**Issue by acomagu** [ms-jpq/chadtree#353]
This is from your README:

![](https://raw.githubusercontent.com/ms-jpq/chadtree/chad/docs/img/git_showcase.gif)

The right side seems terminal emulator, but the result of commands are folded. How is it achieved? Other plugin?

**Comment by niomate** [comment]
You might want to check out [the powerlevel10k theme for zsh](https://github.com/romkatv/powerlevel10k)

**Comment by acomagu** [comment]
@niomate OK, I thought all the output of the command was folded, but in fact only the prompt is compressed. Thank you for your information!
