### ISSUE TITLE
$LS_COLORS is not applied when termguicolors set.

### ISSUE THREAD

**Issue by relastle** [ms-jpq/chadtree#37]
Hi, thank you for developing and maintaining such a cool plugin.

When `termguicolors` is set ( :set termguicolors), the color of chadtree becomes disable.

| notermguicolors | termguicolors |
| --- | --- |
|<img width="1244" alt="Screen Shot 2020-08-06 at 9 36 41" src="https://user-images.githubusercontent.com/6816040/89477531-7aafe400-d7c8-11ea-9015-032a6ff90421.png"> | <img width="1240" alt="Screen Shot 2020-08-06 at 9 36 52" src="https://user-images.githubusercontent.com/6816040/89477529-7a174d80-d7c8-11ea-8e55-7e78f00b2698.png"> | 

Here is a minimal set for reproducing,

***init.vim***

```vim
call plug#begin('~/.vim/plugged')
Plug 'ms-jpq/chadtree', {'branch': 'chad', 'do': ':UpdateRemotePlugins'}
call plug#end()

set termguicolors

```

***$LS_COLORS***

```bash
export LS_COLORS='di=0;36:fi=0:ln=31:pi=5:so=5:bd=5:cd=5:or=31:mi=0:ex=0;32:*.rpm=0:*.tar=0;31'
```

I'm not sure resolving this problem is possible as I have not yet looked into the source codes in details..., but the solution will make the plugin more splendid.

Thank you.

**Comment by ms-jpq** [comment]
I think I fixed it,

can you try now?

https://github.com/ms-jpq/chadtree/commit/fd3672a3cdae5327c3d223c12292789fd3595018

**Comment by grem11n** [comment]
I had the same problem and I can confirm that this issue is resolved in the recent `chad` branch. I'm on `b0ddcfbe4a2b3225abf30332a3a4ea19a72aabb3`

**Comment by relastle** [comment]
@ms-jpq 

Thank you for the response.

| termguicolors | notermguicolors | ls -alh |
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/6816040/89519795-e1a8b980-d817-11ea-8688-bf3a399c03e0.png) | ![image](https://user-images.githubusercontent.com/6816040/89519829-eff6d580-d817-11ea-94d3-f25ad010c6af.png) | ![image](https://user-images.githubusercontent.com/6816040/89533777-e62c9c80-d82e-11ea-8581-4442b6a9f4e6.png)|


Although the color was rendered in `termguicolors`, the color seems different from that in `notermguicolors` and in `ls -alh`.

**Comment by ms-jpq** [comment]
I can't do too much about the display being different, thats a Vim issue, so I did the next best thing.

I added ability to use custom hexcodes in mapping 8bit to 24bit colours.

I can technically try using raw escape codes, but im 99% sure it would run into edge cases for at least a few terminal programs, so thats a bad idea.

The section of how to customize is [here](https://github.com/ms-jpq/chadtree#colours) in the README

**Comment by relastle** [comment]
@ms-jpq 

Thank you for providing global variable for customization.

By making 24-bit colors compatible to my own terminal ANSI color, the problem was solved easily.

```vim
let g:chadtree_colours = {
      \ "8_bit": {
      \   "Black":         { "hl24": "#07242c", "hl8": "Black"},
      \   "Red":           { "hl24": "#fc6195", "hl8": "DarkRed" },
      \   "Green":         { "hl24": "#5AC6A1", "hl8": "DarkGreen" },
      \   "Yellow":        { "hl24": "#fff1ac", "hl8": "DarkYellow" },
      \   "Blue":          { "hl24": "#296873", "hl8": "DarkBlue" },
      \   "Magenta":       { "hl24": "#85919b", "hl8": "DarkMagenta" },
      \   "Cyan":          { "hl24": "#04a7a7", "hl8": "DarkCyan" },
      \   "White":         { "hl24": "#c4c7c7", "hl8": "LightGray" },
      \   "BrightBlack":   { "hl24": "#142c35", "hl8": "Grey" },
      \   "BrightRed":     { "hl24": "#fc81a5", "hl8": "LightRed" },
      \   "BrightGreen":   { "hl24": "#233439", "hl8": "LightGreen" },
      \   "BrightYellow":  { "hl24": "#DF7353", "hl8": "LightYellow" },
      \   "BrightBlue":    { "hl24": "#6FaEaF", "hl8": "LightBlue" },
      \   "BrightMagenta": { "hl24": "#364f6b", "hl8": "LightMagenta" },
      \   "BrightCyan":    { "hl24": "#94e7e7", "hl8": "LightCyan" },
      \   "BrightWhite":   { "hl24": "#dafafc", "hl8": "White" },
      \ }}
```

**Comment by ms-jpq** [comment]
so if you are leaving hl8 the same, you can actually leave it out of the dictionary:)
