### ISSUE TITLE
Feature request: Close parent folder

### ISSUE THREAD

**Issue by Mohammer5** [ms-jpq/chadtree#40]
## Summary

It would be nice to be able to close the parent directory of the file under the cursor, which would speed up navigating the tree quite a bit. NERDTree offers the `x` key mapping, which is quite convenient. The `collapse` command closes sub-folders, no command for closing the parent folder available.

## Desired outcome

A key binding is added to collapse the parent folder.

Possible candidates: `P`, `X`, ``<s-`>``

`P` for "parent", upper-case because `p` is already in use
`X` for convenience, upper-case because `x` is already in use
``<s-`>`` as `` ` `` is used for collapsing sub folders

If none of these are acceptable, no default should be fine as well

**Comment by ms-jpq** [comment]
done I just added the feature to the normal collapse key.

https://github.com/ms-jpq/chadtree/commit/6352de030b5ab11248d895230102db77cad0e535

it wasn't doing anything previously if you did it over a file, now it does what you suggests

**Comment by ms-jpq** [comment]
Improved it a bit,

it now focus your cursor onto the collapsed folder 

https://github.com/ms-jpq/chadtree/commit/9ea91d813b6c9749aea8930e0bdc3ac7ad3f94f7

**Comment by Mohammer5** [comment]
:tada: cheers
