### ISSUE TITLE
`expand` returns an empty string

### ISSUE THREAD

**Issue by bpingris** [ms-jpq/chadtree#41]
Hello !

When I'm in the CHADtree buffer, if I call the `expand` function, it returns me an empty string.
```
: echom expand('%')
``` 

It would be great if it could return something like 'CHADtree' as it's useful for some custom behaviors.

For instance, I'm trying to not use the CHADtree buffer if I open a file with `fzf`. 

With nerdtree you can do something like [this](https://github.com/junegunn/fzf/issues/453#issuecomment-354634207)

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/commit/5248fcb9c1b1d9dd3f56675714a79f185b99454b

done

**Comment by ms-jpq** [comment]
SORRY IT HAD A BUG I NEED TO REVERT IT.

**Comment by ms-jpq** [comment]
Please use `&ft == 'CHADTree'`

I didn't set a buffer name because some plugins *cough cough netrw* will try to `expand(<afile>)` on `BufEnter` and run code. I don't want to cause unnecessary conflicts.
