### ISSUE TITLE
Feature Request: Reveal in file tree. Show line numbers in CHADTree buffer.

### ISSUE THREAD

**Issue by ricbermo** [ms-jpq/chadtree#42]
Hello. Thanks for this package and sharing it with the world.

I was wondering if you kindly could include 2 features I found very important in my workflow.

1. is reveal in CHADTree.
2. Show line numbers in the buffer so I can easily jump from A to B using the navigation keys.

Thanks in advance.

**Comment by ms-jpq** [comment]
can you please explain what do you mean by is reveal?

i have no idea what its supposed to do, do you mean by opening in macos finder or something? 

you can already do that by pressing the o key

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/commit/f83ec3e6605290d0f725a51fc413c1742735aafd

I added the line number thing by allowing you to custom window options.

do

```vimL
lua vim.api.nvim_set_var("chadtree_view", { window_options = {"relativenumber", ...} })
```

with `window_options` being whatever you want to set to chadtree windows
and `...` being whatever else you want to set.

**Comment by ricbermo** [comment]
@ms-jpq thank you so much that new change. About `reveal`, now that I read it, it makes no sense 😅 .
The `reveal` is just a way to go to CHADTree and focus the current file using a command or function. It's not opening the file in the file manager, but within CHADTree.

**Comment by ms-jpq** [comment]
oh, you can already do that with J key, if you turn follow mode on.

but it doesnt work with follow mode off, i will need to rewrite the rendering trigger to do that, probably not gonna happen for a while.

edit: i can do it without rewrite, but it be ugly code

**Comment by ricbermo** [comment]
gotcha. Ty sir for you amazing work. Closing..

**Comment by ms-jpq** [comment]
nono leave it open, I will add the feature in.

also, [not a sir](https://github.com/ms-jpq/ms-jpq) :p

**Comment by ricbermo** [comment]
my bad, I shouldn't have assumed that. So sorry.

**Comment by ms-jpq** [comment]
no problem 👍

**Comment by ms-jpq** [comment]
done 

https://github.com/ms-jpq/chadtree/commit/c4c3fb28a10020c505f869223ef7833ab3d114b8

**Comment by ricbermo** [comment]
TY very much. How do I use it? 😅 follow mode ON + J?

**Comment by ms-jpq** [comment]
just press J, doesnt matter if follow mode is on

**Comment by ricbermo** [comment]
@ms-jpq I may be doing something wrong but it's not working for me.
1. I made sure I updated the plugin.
2. if I press `J` on a buffer it won't open CHADTree with the current file in buffer selected.
3. if I go to the CHADTree buffer and I press J, it does take me to the file.

Am I missing something?
Thanks in advance.

**Comment by ms-jpq** [comment]
oh it only works in chadtree, the J key in normal buffers is an edit command (it joins lines together), i dont think its a good idea for me to override it

**Comment by ricbermo** [comment]
Agree, yeah, I had noticed that. I just need to adjust my brains to the new workflow. TY so much!!!
