### ISSUE TITLE
Icons do not appear properly

### ISSUE THREAD

**Issue by moshiur-raj** [ms-jpq/chadtree#46]
Icons are rendered as blocks. I am using neovim 0.4.4 on archlinux. I have a pretty minimal arch installation so it might just be that I don't have the right font package installed.
![Screenshot from 2020-08-10 10-43-49](https://user-images.githubusercontent.com/36466700/89752595-df37af80-daf6-11ea-97fd-d92253760246.png)

**Comment by ms-jpq** [comment]
Yeah you need to install the fonts:

https://github.com/ryanoasis/nerd-fonts

**Comment by juserdigg** [comment]
Remember to set your console emulators (Konsole or gnuterminal forexample) font to a font (Iosevka or VictorMono forexample) downloaded from the site above.
