### ISSUE TITLE
chadtree doesnt respect new chad-window-size when it gets resized with the mouse

### ISSUE THREAD

**Issue by astier** [ms-jpq/chadtree#47]
### Info

- `NVIM v0.5.0-622-gf26df8bb6`
- `Arch Linux`

### Vimrc

```vim
set runtimepath+=~/.local/share/nvim/plugins/chadtree
set mouse=a
```

### Reproduction

1. `:CHADopen<cr>`
2. Resize chad-window with the mouse
3. Select in chadtree a file and open it with `<cr>`

### Actual Behavior

After opening a file chadtree gets resized to the default chadtree-width.

### Expected Behavior

After opening a file chadtree should keep its new width which was adjusted with the mouse.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/101
