### ISSUE TITLE
Open file/directory with a single click

### ISSUE THREAD

**Issue by astier** [ms-jpq/chadtree#48]
I would like to open a file/directory with a single `<leftmouse>` click. I tried configuring it as you can see in the following vimc:

```vim
set runtimepath+=~/.local/share/nvim/plugins/chadtree
set mouse=a
lua vim.api.nvim_set_var("chadtree_settings", { keymap = { primary = {"<leftmouse>"} }})
```

However, this doesn't work properly. Instead of moving the cursor to the file/dir which I clicked on and opening the respective file/dir, the cursor doesn't move and opens instead the file/dir which it was placed on before clicking on another file/dir.

**Comment by ms-jpq** [comment]
don't think this is actually possible imo.

I need to capture the event for mouse click, but if I do, vim doesn't. So it can't position the mouse on the right row
