### ISSUE TITLE
Ask user for a new filename when the destination file already exists

### ISSUE THREAD

**Issue by Frederick888** [ms-jpq/chadtree#50]
I often need to duplicate a file in the same directory and then modify the new file. Right now if I select a file then `p` in the same place, CHADTree only tells me that the file already exists then aborts the operation. It'd be great if it can suggest a new name and allow users to modify the suggested name.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/72

will close

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/72
