### ISSUE TITLE
Improve default colorscheme visibility

### ISSUE THREAD

**Issue by ecly** [ms-jpq/chadtree#60]
I'm looking into becoming a **chad** instead of a **nerd**, but was initially thrown off by the default colorscheme.
I use [gruvbox](https://github.com/morhetz/gruvbox) dark with hard contrast, and the default folder colors are barely visible.
Some icons take on the same color as filenames.
I realize that the colors can be configured, but I think a slightly more _nerdy_ default colorscheme might help.

**chad** left, **nerd** right.
![1597600275](https://user-images.githubusercontent.com/8410422/90340696-8af66900-dfe9-11ea-9adf-9631e576823e.png)

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/101

will close

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/blob/future2/docs/THEME.md

Sneak peak

**Comment by marcusbuffett** [comment]
This still seems to be an issue for me w/ gruvbox on neovim. The color of a folder in ls output is blue, but contrasts with the background, whereas the blue that chadtree uses is really dark. Let me know if any more info would be helpful. Color nitpicking aside, awesome plugin, thank you!

**Comment by ms-jpq** [comment]
ok im gonna add in more colour schemes, 

just gibe me some time, havnt slept in like 20 hours

**Comment by ms-jpq** [comment]
added more colours

https://github.com/ms-jpq/chadtree/pull/142

Please check the docs on how to config themes:

https://github.com/ms-jpq/chadtree/blob/chad/docs/THEME.md

There are lots of them in there

```json
[
  "env",
  "solarized_dark_256",
  "solarized_dark",
  "solarized_light",
  "solarized_universal",
  "nord",
  "trapdoor",
  "nerdtree_syntax_light",
  "nerdtree_syntax_dark"
]
```

I think im done with this for now, unless you have a specific theme in mind that you think I should add please open another issue. And I ill see if I can import it natively
