### ISSUE TITLE
Sort order of files different from Netrw and terminal

### ISSUE THREAD

**Issue by JonasRSV** [ms-jpq/chadtree#65]
Is it possible to make CHADTree sort files alphabetically.. 

I provide some image examples. I would very much like if it was possible to get the same order in CHADTree as in the other ones! :) 

![chadtree](https://imgur.com/RwlaQ1X.png)

![netrw](https://imgur.com/FcQxEzx.png)

![terminal](https://imgur.com/ojdDOzT.png)

Otherwise I love this plugin, thanks!

**Comment by ms-jpq** [comment]
Added a `sort_by` option :D

https://github.com/ms-jpq/chadtree/blob/chad/config/config.json#L44
