### ISSUE TITLE
Open file in new tab, horizontal split, vertical split, etc

### ISSUE THREAD

**Issue by fsareshwala** [ms-jpq/chadtree#7]
Nice plugin, looks very promising. Some features missing that I need before I can see myself using it.

- Open file in new tab
- Open file in horizontal split
- Open file in vertical split

Really enjoy the speed. It's already faster than NERDTree. Will be watching this plugin and plan to use it when it is more mature.

**Comment by ms-jpq** [comment]
added all three, need to do `:UpdateRemotePlugins` before you can use them tho.

keybinds are in the `Keybindings` section of `README`, feel free to rebind them. I don't know if my defaults are good for these three.
