### ISSUE TITLE
CHADTree gets re-centred to pwd when a floating window is opened

### ISSUE THREAD

**Issue by Frederick888** [ms-jpq/chadtree#71]
For instance, with fzf.vim and CHADTree, first centre CHADTree root to a sub-directory with `c`, then back in main editing window, open e.g. `:Rg`.

Result being CHADTree getting re-centred to pwd, and remaining that way even after fzf floating window is closed.

**Comment by ms-jpq** [comment]
`fzf` emits a `DirChanged` event by doing a `:cd ...`


https://github.com/junegunn/fzf/blob/1a76bdf8914195ab26ebac7e49a3ed8752dd69bd/plugin/fzf.vim#L657


Im not going to add an exception to this, its not possible for me to detect every single plugin that does a `cd`.
