### ISSUE TITLE
Add imgbot on the repo

### ISSUE THREAD

**Issue by Mte90** [ms-jpq/chadtree#73]
https://imgbot.net/ detect that some images can be optimized

**Comment by ms-jpq** [comment]
![图片](https://user-images.githubusercontent.com/50598611/99378589-72ae1880-287c-11eb-8876-01257a8209bd.png)

sorry, its only 13MB of images, unless you are in China, in which case I have an issue to setup a mirror for the GFW, I dont think the size is an issue.

ima close this one.
