### ISSUE TITLE
Lost folder, file colors when source to $MYVIMRC

### ISSUE THREAD

**Issue by ngocthienvnn** [ms-jpq/chadtree#74]
Each time i call `:source $MYVIMRC`, all the colors in Chadtree disappear, and are overwritten with default color of text. Is there any way to fix it?

**Comment by ms-jpq** [comment]
So I am unable to produce this with a clean `$MYVIMRC`.

I am almost certainly sure it's one of your themes or something calling `highlight clear`.

For example the `noctu` colour scheme does this:

https://github.com/noahfrederick/vim-noctu/blob/de2ff9855bccd72cd9ff3082bc89e4a4f36ea4fe/colors/noctu.vim#L9

They do it to enforce their own colour scheme at the cost of killing everybody else's.

I understand why they do it, its an easy way to clear out the default highlights, but it should only be done once, before all the other plugins add in their colour.

You should ask the plugin author to add in a check, which alot of plugins have which is to say `if I was sourced, don't run myself again.`
