### ISSUE TITLE
No ability to disable honoring gitignore patterns

### ISSUE THREAD

**Issue by fsareshwala** [ms-jpq/chadtree#8]
I might have a bit of an odd use case which currently prevents me from using this plugin entirely. I track my entire home directory within git and have a `.gitignore` file containing just `*` so that everything is ignored by default. I can then add what I want into git's view via `git add -f <file>`. However, what this means is that unless a file or directory is tracked via git, chadtree won't display it. For the most part, this is a good feature and probably okay as a default. However, in this specific use case, I'm unable to access any other file unless I show hidden files. I don't want to see all my dotfiles, just untracked files and directories. There should be a way to turn off the honoring of `.gitignore` for specific directories or something.

**Comment by ms-jpq** [comment]
I added `toggle_version_control`, it is not currently bound to any keys. that should make it work for you.

This should be less confusing than trying to set up ignoring `git` on specific directories.

Please update and do `:UpdateRemotePlugins`, then it should all work
