### ISSUE TITLE
Replace netrw with CHADtree

### ISSUE THREAD

**Issue by asd-noor** [ms-jpq/chadtree#89]
Can I replace netrw with CHADtree? I mean, while opening a directory, CHADtree gets loaded in the buffer instead of netrw. NERDtree, fern - they all have this functionality, hijacking netrw.

**Comment by asd-noor** [comment]
Figured out with autocommand!

**Comment by samrathchadha** [comment]
Hey @darrSonik could you send your autocmd?

**Comment by asd-noor** [comment]
@samrath2007
```
augroup Chad
    autocmd!
    autocmd StdinReadPre * let s:std_in=1
    autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'CHADopen' | wincmd p | ene | exe 'cd '.argv()[0] | endif
augroup END
```

**Comment by samrathchadha** [comment]
Thanks
