### ISSUE TITLE
Automatically show line number and relative line number on CHADTree open

### ISSUE THREAD

**Issue by thanhnguyen2187** [ms-jpq/chadtree#90]
Hi.

I am enjoying CHADTree so far. It has everything I wanted for a Vim tree explorer and file manager, except for one thing: line number and relative line number. Here are my CHADTree configuration lines within Vim Plug:

```
    Plug 'ms-jpq/chadtree', {'branch': 'chad', 'do': ':UpdateRemotePlugins'}
        autocmd vimenter * CHADopen
        autocmd FileType CHADtree setlocal number relativenumber
        let g:chadtree_settings={'width': 28}
```
Manual `set` works (type `:set nu rnu`), but it is not my preferred way. Can you please show me a good solution?

Thanks for the great plugin and have a nice day.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/101

will close

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/blob/chad/docs/CONFIGURATION.md

check under `chadtree_settings.view.window_options`
