### ISSUE TITLE
Access internal functions/variables

### ISSUE THREAD

**Issue by Rintse** [ms-jpq/chadtree#92]
I've been looking for alternatives to NERDTree, and this seems like a good candidate, but I need access to some of CHADTree's internals for some customizations that I've grown accustomed to in NERDTree.

For example:
I have a function that gets the currently highlighted item from NERDTree and sets the vim `cwd` to this (if it is a directory), before synching the tree's root with the new `cwd`.

This requires access to `g:NERDTreeFileNode.GetSelected().path`, and variables like it. Is there some way to access similar internals for CHADTree?

**Comment by ms-jpq** [comment]
oh hey, if you press the `y` key, it will copy the file / folder path under cursor to your clipboard in the `*` and `+` registers.

I will not change this, and you can easily make a key macro that does the requested behaviour.

On the other hand, I am nervous about exposing `CHADTree`'s internals. I kind of don't want people to rely on implementation details, or exposing too large of an interface.

I hope this helps you!

**Comment by Rintse** [comment]
Totally missed that y copies the entire path.
I understand your concern exposing the internals. 

I'll see if I can make it work.
