### ISSUE TITLE
Check if currently inside CHADTree

### ISSUE THREAD

**Issue by Rintse** [ms-jpq/chadtree#93]
Since the buffer name is empty, how can I check if I'm currently inside of the CHADTree in a vim script?

**Comment by GGCristo** [comment]
Do
```
set ft?
```
As you can see you can use the ```&ft``` variable

**Comment by ms-jpq** [comment]
yeah `ft`is the best.

Please use `&ft == 'CHADTree'`

I didn't set a buffer name because some plugins *cough cough netrw* will try to `expand(<afile>)` on `BufEnter` and run code. I don't want to cause unnecessary conflicts.
