### ISSUE TITLE
The Plugin will support Vim?

### ISSUE THREAD

**Issue by gVimer** [ms-jpq/chadtree#99]
It seems that this plugin only supports nVim。I want to use it in Vim but not support

**Comment by wysiecki** [comment]
same question ;-(

**Comment by ms-jpq** [comment]
Not for now.

The reason is that I still have one more project I want to finish before I do a port, and I really want that one out of the door first.

I have another issue open for this and I will close this one.

https://github.com/ms-jpq/chadtree/issues/52
